[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# Adds a field to know the Origin-Area(-Type) of Boosters & Vouchers

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "draw_card(G.hand, G.play, 1, 'up', true, card, nil, true)"
position = "before"
payload = "if card then card.SEMBY_origin = area and area.config and area.config.type or 'new' end"
match_indent = true
